name: Website Health Check

on: push

jobs:
  health-check:
    runs-on: ubuntu-latest
    steps:
    - name: Check Website Health
      uses: theritikchoure/websentry@main
      with:
        website-url: 'https://yourwebsite.com'
        max-retries: 3
        retry-interval: 5
        request-timeout: 10
